-- Cadastro mestre e propagacao da categoria escolhida na licitacao.
-- O nome normalizado bloqueia duplicatas por caixa, acentos e espacos repetidos.
create table if not exists public.categorias_licitacao (
  id bigint generated by default as identity primary key,
  nome text not null check (length(btrim(nome)) between 2 and 120),
  nome_chave text generated always as (
    upper(
      regexp_replace(
        translate(
          btrim(nome),
          'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
          'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc'
        ),
        '[[:space:]]+',
        ' ',
        'g'
      )
    )
  ) stored,
  ordem integer not null default 0,
  ativo boolean not null default true,
  revisado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.categorias_licitacao is
  'Categorias mestre escolhidas na licitacao e herdadas por itens, contratos e atas.';

create unique index if not exists categorias_licitacao_nome_chave_uidx
  on public.categorias_licitacao (nome_chave);
create index if not exists categorias_licitacao_ativas_ordem_idx
  on public.categorias_licitacao (ativo, ordem, nome);

insert into public.categorias_licitacao (nome, ordem, ativo, revisado)
values
  ('MATERIAL HOSPITALAR', 1, true, true),
  ('MATERIAL DE ENFERMAGEM', 2, true, true),
  ('MATERIAL ODONTOLÓGICO', 3, true, true),
  ('EQUIPAMENTO MÉDICO-HOSPITALAR', 4, true, true),
  ('EQUIPAMENTO MÉDICO-ODONTOLÓGICO', 5, true, true),
  ('MEDICAMENTOS', 6, true, true),
  ('GASES MEDICINAIS', 7, true, true),
  ('EPI', 8, true, true),
  ('MATERIAL DE CONSUMO', 9, true, true),
  ('LIMPEZA E HIGIENE', 10, true, true),
  ('RESÍDUOS DE SAÚDE', 11, true, true),
  ('UNIFORMES', 12, true, true),
  ('MATERIAL DE EXPEDIENTE', 13, true, true),
  ('UTENSÍLIOS', 14, true, true),
  ('MOBILIÁRIO', 15, true, true),
  ('ELETRODOMÉSTICOS', 16, true, true),
  ('ELETROELETRÔNICOS', 17, true, true),
  ('INFORMÁTICA', 18, true, true),
  ('MANUTENÇÃO DE EQUIPAMENTOS', 19, true, true),
  ('MANUTENÇÃO PREDIAL', 20, true, true),
  ('ENGENHARIA / OBRAS', 21, true, true),
  ('LOCAÇÃO', 22, true, true),
  ('TRANSPORTE', 23, true, true),
  ('SERVIÇOS TERCEIRIZADOS', 24, true, true),
  ('SEGURANÇA', 25, true, true)
on conflict (nome_chave) do update
set ordem = excluded.ordem,
    ativo = true,
    revisado = true,
    updated_at = now();

alter table public.processos add column if not exists categoria_id bigint;
alter table public.itens add column if not exists categoria_id bigint;
alter table public.contratos add column if not exists categoria_id bigint;
alter table public.atas_itens add column if not exists categoria_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'processos_categoria_id_fkey') then
    alter table public.processos
      add constraint processos_categoria_id_fkey foreign key (categoria_id)
      references public.categorias_licitacao(id) on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'itens_categoria_id_fkey') then
    alter table public.itens
      add constraint itens_categoria_id_fkey foreign key (categoria_id)
      references public.categorias_licitacao(id) on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'contratos_categoria_id_fkey') then
    alter table public.contratos
      add constraint contratos_categoria_id_fkey foreign key (categoria_id)
      references public.categorias_licitacao(id) on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'atas_itens_categoria_id_fkey') then
    alter table public.atas_itens
      add constraint atas_itens_categoria_id_fkey foreign key (categoria_id)
      references public.categorias_licitacao(id) on update cascade on delete restrict;
  end if;
end
$$;

create index if not exists processos_categoria_id_idx on public.processos (categoria_id);
create index if not exists itens_categoria_id_idx on public.itens (categoria_id);
create index if not exists contratos_categoria_id_idx on public.contratos (categoria_id);
create index if not exists atas_itens_categoria_id_idx on public.atas_itens (categoria_id);

create or replace function private.herdar_categoria_licitacao()
returns trigger
language plpgsql
set search_path = pg_catalog, public, private
as $$
declare
  v_categoria_id bigint;
begin
  if tg_table_name = 'itens' and new.processo_id is not null then
    select p.categoria_id into v_categoria_id
      from public.processos p where p.id = new.processo_id;
    new.categoria_id := v_categoria_id;
  elsif tg_table_name = 'contratos' and new.processo_id is not null then
    select p.categoria_id into v_categoria_id
      from public.processos p where p.id = new.processo_id;
    new.categoria_id := v_categoria_id;
  elsif tg_table_name = 'atas_itens' and new.contrato_id is not null then
    select c.categoria_id into v_categoria_id
      from public.contratos c where c.id = new.contrato_id;
    new.categoria_id := v_categoria_id;
  end if;
  return new;
end;
$$;

create or replace function private.propagar_categoria_licitacao()
returns trigger
language plpgsql
set search_path = pg_catalog, public, private
as $$
begin
  if tg_table_name = 'processos' then
    update public.itens
       set categoria_id = new.categoria_id
     where processo_id = new.id
       and categoria_id is distinct from new.categoria_id;
    update public.contratos
       set categoria_id = new.categoria_id
     where processo_id = new.id
       and categoria_id is distinct from new.categoria_id;
  elsif tg_table_name = 'contratos' then
    update public.atas_itens
       set categoria_id = new.categoria_id
     where contrato_id = new.id
       and categoria_id is distinct from new.categoria_id;
  end if;
  return null;
end;
$$;

revoke all on function private.herdar_categoria_licitacao() from public, anon, authenticated;
revoke all on function private.propagar_categoria_licitacao() from public, anon, authenticated;

drop trigger if exists trg_itens_herdar_categoria_licitacao on public.itens;
create trigger trg_itens_herdar_categoria_licitacao
before insert or update of processo_id on public.itens
for each row execute function private.herdar_categoria_licitacao();

drop trigger if exists trg_contratos_herdar_categoria_licitacao on public.contratos;
create trigger trg_contratos_herdar_categoria_licitacao
before insert or update of processo_id on public.contratos
for each row execute function private.herdar_categoria_licitacao();

drop trigger if exists trg_atas_itens_herdar_categoria_licitacao on public.atas_itens;
create trigger trg_atas_itens_herdar_categoria_licitacao
before insert or update of contrato_id on public.atas_itens
for each row execute function private.herdar_categoria_licitacao();

drop trigger if exists trg_processos_propagar_categoria_licitacao on public.processos;
create trigger trg_processos_propagar_categoria_licitacao
after update of categoria_id on public.processos
for each row
when (old.categoria_id is distinct from new.categoria_id)
execute function private.propagar_categoria_licitacao();

drop trigger if exists trg_contratos_propagar_categoria_licitacao on public.contratos;
create trigger trg_contratos_propagar_categoria_licitacao
after update of categoria_id on public.contratos
for each row
when (old.categoria_id is distinct from new.categoria_id)
execute function private.propagar_categoria_licitacao();

-- Repara registros que eventualmente ja tenham categoria na origem em reaplicacoes.
update public.itens i
   set categoria_id = p.categoria_id
  from public.processos p
 where p.id = i.processo_id
   and i.categoria_id is distinct from p.categoria_id;

update public.contratos c
   set categoria_id = p.categoria_id
  from public.processos p
 where p.id = c.processo_id
   and c.categoria_id is distinct from p.categoria_id;

update public.atas_itens ai
   set categoria_id = c.categoria_id
  from public.contratos c
 where c.id = ai.contrato_id
   and ai.categoria_id is distinct from c.categoria_id;

alter table public.categorias_licitacao enable row level security;

drop policy if exists read_categorias_licitacao on public.categorias_licitacao;
create policy read_categorias_licitacao
on public.categorias_licitacao for select
to authenticated
using (true);

drop policy if exists insert_categorias_licitacao on public.categorias_licitacao;
create policy insert_categorias_licitacao
on public.categorias_licitacao for insert
to authenticated
with check (
  (select private.is_admin_approved())
  or (select can_access_tab('contratos', 'edit'))
  or (select can_access_tab('licitacoes', 'edit'))
  or (select can_access_tab('cadastros', 'edit'))
);

drop policy if exists update_categorias_licitacao on public.categorias_licitacao;
create policy update_categorias_licitacao
on public.categorias_licitacao for update
to authenticated
using ((select private.is_admin_approved()))
with check ((select private.is_admin_approved()));

drop policy if exists delete_categorias_licitacao on public.categorias_licitacao;
create policy delete_categorias_licitacao
on public.categorias_licitacao for delete
to authenticated
using ((select private.is_admin_approved()));

grant select, insert, update, delete on public.categorias_licitacao to authenticated;
grant usage, select on sequence public.categorias_licitacao_id_seq to authenticated;

-- Mantem a ordem das colunas existentes e acrescenta a categoria ao final.
create or replace view public.vw_processos_resumo
with (security_invoker = true)
as
select p.id,
       p.identificador,
       p.tipo,
       p.natureza,
       p.objeto,
       p.modalidade,
       p.status,
       p.secao,
       p.valor_estimado,
       p.observacao,
       p.gera_mais_contratos,
       p.created_at,
       count(i.id)::integer as total_itens,
       coalesce(sum(i.qtde), 0::numeric) as total_qtde,
       coalesce(sum(coalesce(i.valor_contratado, i.valor_estimado, 0::numeric) * coalesce(i.qtde, 1::numeric)), 0::numeric) as total_itens_valor,
       p.tipo_servico,
       p.servico_mensal_itens,
       p.servico_mensal_meses,
       p.servico_mensal_valor_mensal,
       p.servico_mensal_valor_global,
       (select count(*)::integer from public.contratos c where c.processo_id = p.id) as n_contratos,
       p.servico_demanda_meses,
       p.sc,
       p.secao_id,
       p.servico_trimestral_itens,
       p.servico_trimestral_meses,
       p.servico_trimestral_ciclos,
       p.servico_trimestral_valor_trimestral,
       p.servico_trimestral_valor_global,
       p.link_publico_sei,
       p.categoria_id,
       (select cl.nome from public.categorias_licitacao cl where cl.id = p.categoria_id) as categoria_licitacao
  from public.processos p
  left join public.itens i on i.processo_id = p.id
 group by p.id;

comment on column public.processos.categoria_id is 'Categoria mestre escolhida na abertura da licitacao.';
comment on column public.itens.categoria_id is 'Categoria herdada do processo de licitacao.';
comment on column public.contratos.categoria_id is 'Categoria herdada do processo de origem.';
comment on column public.atas_itens.categoria_id is 'Categoria herdada do contrato/ata de origem.';
